# Generated by Django 3.1.7 on 2021-03-30 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 8, 36, 57, 525620, tzinfo=utc)),
        ),
    ]
